#!/bin/sh
#
# A hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

if ! spruce precommit
then
    echo "spruce compliance is now mandatory for iz"
    exit 1
fi
