
/* (c)  oblong industries */

#ifndef SLAW_NUMERIC_ILK_RUMPUS_PRIVATE_GOATPLAY
#define SLAW_NUMERIC_ILK_RUMPUS_PRIVATE_GOATPLAY

// the basics, kid:

#define SLAW_int8 (OB_CONST_U64 (0))
#define SLAW_unt8 (SLAW_int8 | SLAW_NUMERIC_UNSIGNED_FLAG)
#define SLAW_int16 (OB_CONST_U64 (1) << SLAW_NUMERIC_SIZE_SHIFTY)
#define SLAW_unt16 (SLAW_int16 | SLAW_NUMERIC_UNSIGNED_FLAG)
#define SLAW_int32 (OB_CONST_U64 (2) << SLAW_NUMERIC_SIZE_SHIFTY)
#define SLAW_unt32 (SLAW_int32 | SLAW_NUMERIC_UNSIGNED_FLAG)
#define SLAW_int64 (OB_CONST_U64 (3) << SLAW_NUMERIC_SIZE_SHIFTY)
#define SLAW_unt64 (SLAW_int64 | SLAW_NUMERIC_UNSIGNED_FLAG)
#define SLAW_float32 (SLAW_int32 | SLAW_NUMERIC_FLOAT_FLAG)
#define SLAW_float64 (SLAW_int64 | SLAW_NUMERIC_FLOAT_FLAG)



// complex numbah horseplay:

#define SLAW_int32c (SLAW_int32 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_unt32c (SLAW_unt32 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_int64c (SLAW_int64 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_unt64c (SLAW_unt64 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_float32c (SLAW_float32 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_float64c (SLAW_float64 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_int8c (SLAW_int8 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_unt8c (SLAW_unt8 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_int16c (SLAW_int16 | SLAW_NUMERIC_COMPLEX_FLAG)
#define SLAW_unt16c (SLAW_unt16 | SLAW_NUMERIC_COMPLEX_FLAG)



// vector shenanigans:

#define SLAW_v2int32 (SLAW_int32 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt32 (SLAW_unt32 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int64 (SLAW_int64 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt64 (SLAW_unt64 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2float32 (SLAW_float32 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2float64 (SLAW_float64 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int8 (SLAW_int8 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt8 (SLAW_unt8 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int16 (SLAW_int16 | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt16 (SLAW_unt16 | SLAW_NUMERIC_VEC2_BITS)



#define SLAW_v3int32 (SLAW_int32 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt32 (SLAW_unt32 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int64 (SLAW_int64 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt64 (SLAW_unt64 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3float32 (SLAW_float32 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3float64 (SLAW_float64 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int8 (SLAW_int8 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt8 (SLAW_unt8 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int16 (SLAW_int16 | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt16 (SLAW_unt16 | SLAW_NUMERIC_VEC3_BITS)



#define SLAW_v4int32 (SLAW_int32 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt32 (SLAW_unt32 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int64 (SLAW_int64 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt64 (SLAW_unt64 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4float32 (SLAW_float32 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4float64 (SLAW_float64 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int8 (SLAW_int8 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt8 (SLAW_unt8 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int16 (SLAW_int16 | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt16 (SLAW_unt16 | SLAW_NUMERIC_VEC4_BITS)



// complex vector extravaganza:

#define SLAW_v2int32c (SLAW_int32c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt32c (SLAW_unt32c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int64c (SLAW_int64c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt64c (SLAW_unt64c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2float32c (SLAW_float32c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2float64c (SLAW_float64c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int8c (SLAW_int8c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt8c (SLAW_unt8c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2int16c (SLAW_int16c | SLAW_NUMERIC_VEC2_BITS)
#define SLAW_v2unt16c (SLAW_unt16c | SLAW_NUMERIC_VEC2_BITS)



#define SLAW_v3int32c (SLAW_int32c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt32c (SLAW_unt32c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int64c (SLAW_int64c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt64c (SLAW_unt64c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3float32c (SLAW_float32c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3float64c (SLAW_float64c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int8c (SLAW_int8c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt8c (SLAW_unt8c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3int16c (SLAW_int16c | SLAW_NUMERIC_VEC3_BITS)
#define SLAW_v3unt16c (SLAW_unt16c | SLAW_NUMERIC_VEC3_BITS)



#define SLAW_v4int32c (SLAW_int32c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt32c (SLAW_unt32c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int64c (SLAW_int64c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt64c (SLAW_unt64c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4float32c (SLAW_float32c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4float64c (SLAW_float64c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int8c (SLAW_int8c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt8c (SLAW_unt8c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4int16c (SLAW_int16c | SLAW_NUMERIC_VEC4_BITS)
#define SLAW_v4unt16c (SLAW_unt16c | SLAW_NUMERIC_VEC4_BITS)



// multivector multiverse

#define SLAW_m2int32 (SLAW_int32 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2unt32 (SLAW_unt32 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2int64 (SLAW_int64 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2unt64 (SLAW_unt64 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2float32 (SLAW_float32 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2float64 (SLAW_float64 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2int8 (SLAW_int8 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2unt8 (SLAW_unt8 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2int16 (SLAW_int16 | SLAW_NUMERIC_MVEC2_BITS)
#define SLAW_m2unt16 (SLAW_unt16 | SLAW_NUMERIC_MVEC2_BITS)



#define SLAW_m3int32 (SLAW_int32 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3unt32 (SLAW_unt32 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3int64 (SLAW_int64 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3unt64 (SLAW_unt64 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3float32 (SLAW_float32 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3float64 (SLAW_float64 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3int8 (SLAW_int8 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3unt8 (SLAW_unt8 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3int16 (SLAW_int16 | SLAW_NUMERIC_MVEC3_BITS)
#define SLAW_m3unt16 (SLAW_unt16 | SLAW_NUMERIC_MVEC3_BITS)



#define SLAW_m4int32 (SLAW_int32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt32 (SLAW_unt32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int64 (SLAW_int64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt64 (SLAW_unt64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4float32 (SLAW_float32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4float64 (SLAW_float64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int8 (SLAW_int8 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt8 (SLAW_unt8 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int16 (SLAW_int16 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt16 (SLAW_unt16 | SLAW_NUMERIC_MVEC4_BITS)



#define SLAW_m4int32 (SLAW_int32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt32 (SLAW_unt32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int64 (SLAW_int64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt64 (SLAW_unt64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4float32 (SLAW_float32 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4float64 (SLAW_float64 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int8 (SLAW_int8 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt8 (SLAW_unt8 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4int16 (SLAW_int16 | SLAW_NUMERIC_MVEC4_BITS)
#define SLAW_m4unt16 (SLAW_unt16 | SLAW_NUMERIC_MVEC4_BITS)



#define SLAW_m5int32 (SLAW_int32 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5unt32 (SLAW_unt32 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5int64 (SLAW_int64 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5unt64 (SLAW_unt64 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5float32 (SLAW_float32 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5float64 (SLAW_float64 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5int8 (SLAW_int8 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5unt8 (SLAW_unt8 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5int16 (SLAW_int16 | SLAW_NUMERIC_MVEC5_BITS)
#define SLAW_m5unt16 (SLAW_unt16 | SLAW_NUMERIC_MVEC5_BITS)



#endif /* SLAW_NUMERIC_ILK_RUMPUS_PRIVATE_GOATPLAY */
